# Generated by Django 5.2.1 on 2025-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='cost_per_page',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость страницы'),
        ),
    ]
