# Generated by Django 5.2.1 on 2025-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printer_cost_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printevent',
            name='byte_size',
            field=models.IntegerField(default=0, verbose_name='Размер в байтах'),
        ),
    ]
