# Generated by Django 5.2.1 on 2026-02-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0005_add_user_printer_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="printevent",
            new_name="printing_pr_user_id_584d4a_idx",
            old_name="printing_pr_user_id_tim_idx",
        ),
        migrations.RenameIndex(
            model_name="printevent",
            new_name="printing_pr_printer_890fd8_idx",
            old_name="printing_pr_printer_tim_idx",
        ),
    ]
